services:
  desktop:
    image: ${DOCKER_USERNAME:-storytellerf}/desktop-in-docker:${DESKTOP_ENV:-xfce}-snapshot
    ports:
      - "6080" # noVNC web interface
      - "5901" # VNC direct connection
    environment:
      - VNC_GEOMETRY=1920x1080
      - VNC_DEPTH=24
    env_file:
      - .env
    volumes:
      - ./logs:${CONTAINER_HOME:-/home/debian}/log/supervisor
      - bash_history:${CONTAINER_HOME:-/home/debian}/.desktop-in-docker/.bash_history
    shm_size: '2gb' # Allocate more shared memory
    restart: "unless-stopped"

volumes:
  avd_data:
  sdk_data:
    external: true
  bash_history:
