[unix_http_server]
file=%(ENV_HOME)s/run/supervisor.sock

[include]
files = %(ENV_HOME)s/supervisor/conf.d/*.conf

[supervisord]
logfile=%(ENV_HOME)s/log/supervisor/supervisord.log
pidfile=%(ENV_HOME)s/run/supervisord.pid
user=%(ENV_SUPERVISOR_USER)s

[rpcinterface:supervisor]
supervisor.rpcinterface_factory = supervisor.rpcinterface:make_main_rpcinterface

[supervisorctl]
serverurl=unix://%(ENV_HOME)s/run/supervisor.sock

[program:vnc]
command=%(ENV_HOME)s/bin/start-vnc.sh
environment=USER=%(ENV_SUPERVISOR_USER)s,HOME=%(ENV_HOME)s
stdout_logfile=%(ENV_HOME)s/log/supervisor/vnc_stdout.log
stderr_logfile=%(ENV_HOME)s/log/supervisor/vnc_stderr.log
autorestart=false
user=%(ENV_SUPERVISOR_USER)s
stopcommand=%(ENV_HOME)s/bin/vncserver -kill :1
stopwaitsecs=10
stopasgroup=true
killasgroup=true

[program:novnc]
command=/usr/bin/websockify --web /usr/share/novnc/ 6080 localhost:5901
stdout_logfile=%(ENV_HOME)s/log/supervisor/novnc_stdout.log
stderr_logfile=%(ENV_HOME)s/log/supervisor/novnc_stderr.log
autorestart=false
user=%(ENV_SUPERVISOR_USER)s
