[program:fcitx]
command=%(ENV_HOME)s/bin/start-fcitx.sh
environment=USER=%(ENV_SUPERVISOR_USER)s,HOME=%(ENV_HOME)s,DISPLAY=:1
stdout_logfile=%(ENV_HOME)s/log/supervisor/fcitx_stdout.log
stderr_logfile=%(ENV_HOME)s/log/supervisor/fcitx_stderr.log
autorestart=false
user=%(ENV_SUPERVISOR_USER)s
stopasgroup=true
killasgroup=true
