[unix_http_server]
file=%(ENV_HOME)s/run/supervisor.sock

[supervisord]
logfile=%(ENV_HOME)s/log/supervisor/supervisord.log
pidfile=%(ENV_HOME)s/run/supervisord.pid
user=%(ENV_SUPERVISOR_USER)s

[rpcinterface:supervisor]
supervisor.rpcinterface_factory = supervisor.rpcinterface:make_main_rpcinterface

[supervisorctl]
serverurl=unix://%(ENV_HOME)s/run/supervisor.sock

[program:wayland-rdp]
command=%(ENV_HOME)s/bin/start-wayland-rdp.sh
environment=USER=%(ENV_SUPERVISOR_USER)s,HOME=%(ENV_HOME)s,XDG_RUNTIME_DIR=%(ENV_HOME)s/run,XDG_CONFIG_HOME=%(ENV_HOME)s/.config
stdout_logfile=%(ENV_HOME)s/log/supervisor/weston_stdout.log
stderr_logfile=%(ENV_HOME)s/log/supervisor/weston_stderr.log
autorestart=false
user=%(ENV_SUPERVISOR_USER)s
stopwaitsecs=10
stopasgroup=true
killasgroup=true
