[supervisord]
nodaemon=true
logfile=/config/log/supervisor/supervisord.log
pidfile=/config/run/supervisord.pid

[program:fcitx]
command=/usr/local/bin/start-fcitx.sh
user=abc
environment=HOME="/config",XDG_CONFIG_HOME="/config/.config",XMODIFIERS="@im=fcitx",GTK_IM_MODULE="fcitx",QT_IM_MODULE="fcitx"
autostart=true
autorestart=true
stdout_logfile=/config/log/supervisor/fcitx_stdout.log
stderr_logfile=/config/log/supervisor/fcitx_stderr.log
